### ISSUE TITLE
I want to communication with you about the use of HFO and DeepRL_RoboCup

### ISSUE THREAD

**Issue by conquerman** [LiwenZhang0201/DeepRL_RoboCup#1]
I'd like to discuss RoboCup 2D with you very much. Could you please leave your contact information（QQ or wechat） for me to communicate with you？
我非常想和你探讨robocup 2d的相关话题，能不能留一下联系方式，方便和你交流。QQ方便嘛或者wechat.

**Comment by LiwenZhang0201** [comment]
你好，加我微信吧lwzhang201
